### ISSUE TITLE
can't get error message with language

### ISSUE THREAD

**Issue by tidiview** [Perlkonig/grav-plugin-graveyard#3]
for these addresses: `/fr/ikokujin` `/ja/ikokujin` `/en/ikokujin`, I have an error message in french as it is the site default language while pages are in french, japanese and english.
It would be nice to make possible that the error message looks over the language of the desired page over the site's language ☆

**Comment by Perlkonig** [comment]
It should be doing that already. I thought the `|t` twig filter took care of that. I'll have to do a little research.

**Comment by Perlkonig** [comment]
Oh. I see what you're saying. This is more of an issue with Grav itself. AFAIK, Grav can't know for sure the page-specific language if the page doesn't exist. I rely on the `|t` twig filter to route the error message through the translator, so the site default is chosen. Perhaps post this issue over on the Grav repo and see if they can add this in the next version.
